### ISSUE TITLE
ExcelExtractor is failing whenever I try to import an excel file

### ISSUE THREAD

**Issue by cp-mahmoud-heretani** [FlatFilers/flatfile-plugins#329]
### Brief
I'm getting an error whenever I'm trying to import an excel file (both xlsx and xls) using a very minimal example

### Dependencies 
```
"dependencies": {
    "@flatfile/api": "^1.5.34",
    "@flatfile/hooks": "^1.3.2",
    "@flatfile/listener": "^0.3.17",
    "@flatfile/plugin-record-hook": "^1.1.11",
    "@flatfile/plugin-xlsx-extractor": "^1.8.2",
    "@flatfile/react": "^7.2.31",
    "@flatfile/util-extractor": "^0.4.7",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^14.0.0",
    "@testing-library/user-event": "^13.5.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "web-vitals": "^2.1.4",
    "xlsx": "^0.20.0"
  },
```
### Code
sample.ts (listener)
```
import { FlatfileListener } from "@flatfile/listener";
import { recordHook } from "@flatfile/plugin-record-hook";
import { ExcelExtractor } from "@flatfile/plugin-xlsx-extractor";


/**
 * Example Listener
 */
export const listener = FlatfileListener.create((listener) => {

  listener.on("**", (event) => {
    console.log(`Received event: ${event.topic}`);
  });

// Define optional options for the extractor
const options = {
  raw: true,
  rawNumbers: true,
};

// Initialize the Excel extractor
const excelExtractor = ExcelExtractor(options);

// Register the extractor as a middleware for the Flatfile listener
listener.use(excelExtractor);

  listener.use(
    recordHook("flights", (record) => {
      const firstName = record.get("firstName");
      console.log({ firstName });
      record.set("lastName", "Rock");
      return record;
    })
  );

});
``` 
 App.tsx
 ```
import { Dispatch, SetStateAction, useState } from "react";
import { ISpace, useSpace } from "@flatfile/react";
import { workbook } from "./workbook";
import { listener } from "./listeners/simple";

const spaceProps: ISpace = {
  name: "Embedded Space",
  publishableKey: "XXX",
  environmentId: "XXX",
};

const Space = ({
  setShowSpace,
}: {
  setShowSpace: Dispatch<SetStateAction<boolean>>;
}) => {
  const space = useSpace({
    ...spaceProps,
    workbook,
    listener,
    sidebarConfig: {
      showSidebar: false,
    },
    themeConfig: {
      root: {
        primaryColor: "red",
      },
      sidebar: {
        logo: "https://images.ctfassets.net/hjneo4qi4goj/gL6Blz3kTPdZXWknuIDVx/7bb7c73d93b111ed542d2ed426b42fd5/flatfile.svg",
      },
    },
    closeSpace: {
      operation: "submitActionFg",
      onClose: () => setShowSpace(false),
    },
  });
  return space;
};

export default function App() {
  const [showSpace, setShowSpace] = useState(false);

  return (
    <div className="content">
      <h2>
        <code>&lt;Flatfile /&gt;</code>
      </h2>
      <p>Embed Flatfile in just a few lines of code.</p>
      {/*Button to trigger the modal */}
      <div>
        <button
          className="contrast"
          onClick={() => {
            setShowSpace(!showSpace);
          }}
        >
          {showSpace === true ? "Close" : "Open and create new"} Space
        </button>
        {showSpace && <Space setShowSpace={setShowSpace} />}
      </div>
    </div>
  );
}
```
## Bug
Whenever I try to run the code and import an Excel file I get the following error message in my browser (developer mode):
Uncaught runtime errors:

ERROR
Error adding workbook to space: Network Error
    at http://localhost:3000/static/js/bundle.js:149046:11
    at Generator.throw (<anonymous>)
    at rejected (http://localhost:3000/static/js/bundle.js:148709:32)
   
plus this is a screenshot showing the error:
<img width="1483" alt="image" src="https://github.com/FlatFilers/flatfile-plugins/assets/110395474/ba3bcfc6-1598-4c3b-b496-04d48128e74b">

Kindly note that everything works fine when using a CSV file instead of Excel, so could you please advise what to do to make it work?

**Comment by carlbrugger** [comment]
Hi @cp-mahmoud-heretani, the `@flatfile/plugin-xlsx-extractor` is intended [to be run server-side](https://flatfile.com/docs/plugins/extractors/xlsx-extractor). This can be done by following these instructions to run it [locally](https://flatfile.com/docs/developer-tools/developing/running-local) or [deployed](https://flatfile.com/docs/developer-tools/deploying). An example can be [found here](https://github.com/FlatFilers/flatfile-docs-kitchen-sink/blob/main/typescript/extractors/index.ts#L79).
